CREATE TABLE agencies (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO agencies (name) VALUES ('Actuary, NYC Office of the (NYCOA)');
INSERT INTO agencies (name) VALUES ('Administrative Justice Coordinator, NYC Office of (AJC)');
INSERT INTO agencies (name) VALUES ('Administrative Trials and Hearings, Office of (OATH)');
INSERT INTO agencies (name) VALUES ('Aging, Department for the (DFTA)');
INSERT INTO agencies (name) VALUES ('Buildings, Department of (DOB)');
INSERT INTO agencies (name) VALUES ('Business Integrity Commission (BIC)');
INSERT INTO agencies (name) VALUES ('Campaign Finance Board (CFB)');
INSERT INTO agencies (name) VALUES ('Center for Innovation through Data Intelligence (CIDI)');
INSERT INTO agencies (name) VALUES ('Chief Medical Examiner, NYC Office of (OCME)');
INSERT INTO agencies (name) VALUES ('Children''s Services, Administration for (ACS)');
INSERT INTO agencies (name) VALUES ('City Council, New York (NYCC)');
INSERT INTO agencies (name) VALUES ('City Planning, Department of (DCP)');
INSERT INTO agencies (name) VALUES ('Citywide Administrative Services, Department of (DCAS)');
INSERT INTO agencies (name) VALUES ('Civilian Complaint Review Board (CCRB)');
INSERT INTO agencies (name) VALUES ('Combat Domestic Violence, Mayor''s Office to (OCDV)');
INSERT INTO agencies (name) VALUES ('Commission on Gender Equity (CGE)');
INSERT INTO agencies (name) VALUES ('Commission to Combat Police Corruption (CCPC)');
INSERT INTO agencies (name) VALUES ('Community Affairs Unit (CAU)');
INSERT INTO agencies (name) VALUES ('Comptroller (COMP)');
INSERT INTO agencies (name) VALUES ('Conflicts of Interest Board (COIB)');
INSERT INTO agencies (name) VALUES ('Consumer Affairs, Department of (DCA)');
INSERT INTO agencies (name) VALUES ('Contract Services, Mayor''s Office of (MOCS)');
INSERT INTO agencies (name) VALUES ('Correction, Board of (BOC)');
INSERT INTO agencies (name) VALUES ('Correction, Department of (DOC)');
INSERT INTO agencies (name) VALUES ('Criminal Justice, Mayor''s Office of (MOCJ)');
INSERT INTO agencies (name) VALUES ('Cultural Affairs, Department of (DCLA)');
INSERT INTO agencies (name) VALUES ('Data Analytics, Mayor''s Office of (MODA)');
INSERT INTO agencies (name) VALUES ('Design and Construction, Department of (DDC)');
INSERT INTO agencies (name) VALUES ('Economic Development Corporation (EDC)');
INSERT INTO agencies (name) VALUES ('Economic Opportunity, Mayor''s Office for (Opportunity)');
INSERT INTO agencies (name) VALUES ('Education, Department of (DOE)');
INSERT INTO agencies (name) VALUES ('Elections, Board of (BOE)');
INSERT INTO agencies (name) VALUES ('Emergency Management, Office of (OEM)');
INSERT INTO agencies (name) VALUES ('Environmental Coordination, Mayor''s Office of (OEC)');
INSERT INTO agencies (name) VALUES ('Environmental Protection, Department of (DEP)');
INSERT INTO agencies (name) VALUES ('Environmental Remediation, Mayor''s Office of (OER)');
INSERT INTO agencies (name) VALUES ('Equal Employment Practices Commission (EEPC)');
INSERT INTO agencies (name) VALUES ('Finance, Department of (DOF)');
INSERT INTO agencies (name) VALUES ('Fire Department, New York City (FDNY)');
INSERT INTO agencies (name) VALUES ('Food Policy Director, Mayor''s Office of the (MOFP)');
INSERT INTO agencies (name) VALUES ('GreeNYC (GNYC)');
INSERT INTO agencies (name) VALUES ('Health and Hospitals Corporation (HHC)');
INSERT INTO agencies (name) VALUES ('Health and Mental Hygiene, Department of (DOHMH)');
INSERT INTO agencies (name) VALUES ('Homeless Services, Department of (DHS)');
INSERT INTO agencies (name) VALUES ('Housing Authority, New York City (NYCHA)');
INSERT INTO agencies (name) VALUES ('Housing Preservation and Development, Department of (HPD)');
INSERT INTO agencies (name) VALUES ('Housing Recovery Operations (HRO)');
INSERT INTO agencies (name) VALUES ('Human Resources Administration (HRA)');
INSERT INTO agencies (name) VALUES ('Human Rights, City Commission on (CCHR)');
INSERT INTO agencies (name) VALUES ('Immigrant Affairs, Mayor''s Office of (MOIA)');
INSERT INTO agencies (name) VALUES ('Independent Budget Office, NYC (IBO)');
INSERT INTO agencies (name) VALUES ('Information Technology and Telecommunications, Department of (DOITT)');
INSERT INTO agencies (name) VALUES ('Inspector General NYPD, Office of the (OIG-NYPD)');
INSERT INTO agencies (name) VALUES ('Intergovernmental Affairs, Mayor''s Office of (MOIGA)');
INSERT INTO agencies (name) VALUES ('International Affairs, Mayor''s Office for  (IA)');
INSERT INTO agencies (name) VALUES ('Investigation, Department of (DOI)');
INSERT INTO agencies (name) VALUES ('Labor Relations, NYC Office of (OLR)');
INSERT INTO agencies (name) VALUES ('Landmarks Preservation Commission (LPC)');
INSERT INTO agencies (name) VALUES ('Law Department (LAW)');
INSERT INTO agencies (name) VALUES ('Loft Board (LOFT)');
INSERT INTO agencies (name) VALUES ('Long-Term Planning & Sustainability, Office of (OLTPS)');
INSERT INTO agencies (name) VALUES ('Management and Budget, Office of (OMB)');
INSERT INTO agencies (name) VALUES ('Mayor''s Fund to Advance NYC (Mayor''s Fund)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office (OM)');
INSERT INTO agencies (name) VALUES ('Media and Entertainment, Mayor''s Office of (MOME)');
INSERT INTO agencies (name) VALUES ('New Business Acceleration Team (NBAT)');
INSERT INTO agencies (name) VALUES ('NYC & Company (NYCGO)');
INSERT INTO agencies (name) VALUES ('NYC Employees'' Retirement System (NYCERS)');
INSERT INTO agencies (name) VALUES ('NYC Service (SERVICE)');
INSERT INTO agencies (name) VALUES ('Operations, Mayor''s Office of (OPS)');
INSERT INTO agencies (name) VALUES ('Parks and Recreation, Department of (DPR)');
INSERT INTO agencies (name) VALUES ('People with Disabilities, Mayor''s Office of (MOPD)');
INSERT INTO agencies (name) VALUES ('Police Department (NYPD)');
INSERT INTO agencies (name) VALUES ('Police Pension Fund (PPF)');
INSERT INTO agencies (name) VALUES ('Probation, Department of (DOP)');
INSERT INTO agencies (name) VALUES ('Procurement Policy Board (PPB)');
INSERT INTO agencies (name) VALUES ('Public Advocate (PUB ADV)');
INSERT INTO agencies (name) VALUES ('Public Design Commission (DesignCommission)');
INSERT INTO agencies (name) VALUES ('Quadrennial Advisory Commission (QuadAC)');
INSERT INTO agencies (name) VALUES ('Records and Information Services, Department of (DORIS)');
INSERT INTO agencies (name) VALUES ('Recovery & Resiliency, Mayor''s Office of (ORR)');
INSERT INTO agencies (name) VALUES ('Rent Guidelines Board (RGB)');
INSERT INTO agencies (name) VALUES ('Sanitation, Department of (DSNY)');
INSERT INTO agencies (name) VALUES ('Small Business Services, Department of (SBS)');
INSERT INTO agencies (name) VALUES ('Standards and Appeals, Board of (BSA)');
INSERT INTO agencies (name) VALUES ('Sustainability, Mayor''s Office of (Sustainability)');
INSERT INTO agencies (name) VALUES ('Tax Appeals Tribunal, New York City (TAT)');
INSERT INTO agencies (name) VALUES ('Tax Commission, New York City (TC)');
INSERT INTO agencies (name) VALUES ('Taxi and Limousine Commission (TLC)');
INSERT INTO agencies (name) VALUES ('Technology and Innovation, Mayor''s Office of (MOTI)');
INSERT INTO agencies (name) VALUES ('Transportation, Department of (DOT)');
INSERT INTO agencies (name) VALUES ('Veterans'' Services, Department of (DVS)');
INSERT INTO agencies (name) VALUES ('Water Board (NYWB)');
INSERT INTO agencies (name) VALUES ('Water Finance Authority, NYC Municipal (NYW)');
INSERT INTO agencies (name) VALUES ('Waterfront Management Advisory Board (WMAB)');
INSERT INTO agencies (name) VALUES ('Workforce Development, Mayor''s Office of (WKDEV)');
INSERT INTO agencies (name) VALUES ('Workforce Investment Board (WIB)');
INSERT INTO agencies (name) VALUES ('Youth and Community Development, Department of (DYCD)');

CREATE TABLE subjects (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO subjects (name) VALUES ('Accounting');
INSERT INTO subjects (name) VALUES ('Advertising');
INSERT INTO subjects (name) VALUES ('Aged');
INSERT INTO subjects (name) VALUES ('Alcohol');
INSERT INTO subjects (name) VALUES ('Animal Welfare');
INSERT INTO subjects (name) VALUES ('Archaeology');
INSERT INTO subjects (name) VALUES ('Architecture');
INSERT INTO subjects (name) VALUES ('Art and Design');
INSERT INTO subjects (name) VALUES ('Athletics');
INSERT INTO subjects (name) VALUES ('Banks and Banking');
INSERT INTO subjects (name) VALUES ('Brooklyn');
INSERT INTO subjects (name) VALUES ('Bronx');
INSERT INTO subjects (name) VALUES ('Brooklyn (City)');
INSERT INTO subjects (name) VALUES ('Budget and Finance');
INSERT INTO subjects (name) VALUES ('Building Code');
INSERT INTO subjects (name) VALUES ('Building Construction');
INSERT INTO subjects (name) VALUES ('Buildings');
INSERT INTO subjects (name) VALUES ('Business');
INSERT INTO subjects (name) VALUES ('Celebrations and Parades');
INSERT INTO subjects (name) VALUES ('Cemeteries');
INSERT INTO subjects (name) VALUES ('Census');
INSERT INTO subjects (name) VALUES ('Charities');
INSERT INTO subjects (name) VALUES ('Children');
INSERT INTO subjects (name) VALUES ('City Planning');
INSERT INTO subjects (name) VALUES ('Civil Service');
INSERT INTO subjects (name) VALUES ('Climate');
INSERT INTO subjects (name) VALUES ('Coastal');
INSERT INTO subjects (name) VALUES ('Community Relations');
INSERT INTO subjects (name) VALUES ('Consumers');
INSERT INTO subjects (name) VALUES ('Conventions');
INSERT INTO subjects (name) VALUES ('Correction');
INSERT INTO subjects (name) VALUES ('Cost');
INSERT INTO subjects (name) VALUES ('Courts');
INSERT INTO subjects (name) VALUES ('Crime and Criminals');
INSERT INTO subjects (name) VALUES ('Criminal Justice');
INSERT INTO subjects (name) VALUES ('Culture');
INSERT INTO subjects (name) VALUES ('Data and Communications');
INSERT INTO subjects (name) VALUES ('Death');
INSERT INTO subjects (name) VALUES ('Demography and Population');
INSERT INTO subjects (name) VALUES ('Disability');
INSERT INTO subjects (name) VALUES ('Discrimination');
INSERT INTO subjects (name) VALUES ('Diseases');
INSERT INTO subjects (name) VALUES ('Drugs');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Elections and Voting');
INSERT INTO subjects (name) VALUES ('Electric Power');
INSERT INTO subjects (name) VALUES ('Emergencies');
INSERT INTO subjects (name) VALUES ('Employment');
INSERT INTO subjects (name) VALUES ('Energy');
INSERT INTO subjects (name) VALUES ('Engineering');
INSERT INTO subjects (name) VALUES ('Environment');
INSERT INTO subjects (name) VALUES ('Equal Employment');
INSERT INTO subjects (name) VALUES ('Ethics');
INSERT INTO subjects (name) VALUES ('Ethnic groups');
INSERT INTO subjects (name) VALUES ('Families');
INSERT INTO subjects (name) VALUES ('Finance');
INSERT INTO subjects (name) VALUES ('Fire Fighting');
INSERT INTO subjects (name) VALUES ('Firearms');
INSERT INTO subjects (name) VALUES ('Food');
INSERT INTO subjects (name) VALUES ('Food supply');
INSERT INTO subjects (name) VALUES ('Fuels');
INSERT INTO subjects (name) VALUES ('Gambling');
INSERT INTO subjects (name) VALUES ('Geography');
INSERT INTO subjects (name) VALUES ('Government');
INSERT INTO subjects (name) VALUES ('Government - Citizen participation');
INSERT INTO subjects (name) VALUES ('Hazardous Materials');
INSERT INTO subjects (name) VALUES ('Health');
INSERT INTO subjects (name) VALUES ('History');
INSERT INTO subjects (name) VALUES ('Homeless Persons');
INSERT INTO subjects (name) VALUES ('Hospitals');
INSERT INTO subjects (name) VALUES ('Hotels');
INSERT INTO subjects (name) VALUES ('Housing');
INSERT INTO subjects (name) VALUES ('Housing - Limited Profit');
INSERT INTO subjects (name) VALUES ('Housing - Low Income');
INSERT INTO subjects (name) VALUES ('Human Rights');
INSERT INTO subjects (name) VALUES ('Immigration');
INSERT INTO subjects (name) VALUES ('Industries');
INSERT INTO subjects (name) VALUES ('Infrastructure');
INSERT INTO subjects (name) VALUES ('Insurance');
INSERT INTO subjects (name) VALUES ('Internet');
INSERT INTO subjects (name) VALUES ('Islands');
INSERT INTO subjects (name) VALUES ('Labor and Employment');
INSERT INTO subjects (name) VALUES ('Land Use');
INSERT INTO subjects (name) VALUES ('Landmarks');
INSERT INTO subjects (name) VALUES ('Languages');
INSERT INTO subjects (name) VALUES ('Laws and legislation');
INSERT INTO subjects (name) VALUES ('LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)');
INSERT INTO subjects (name) VALUES ('Libraries');
INSERT INTO subjects (name) VALUES ('Licenses and Permits');
INSERT INTO subjects (name) VALUES ('Manhattan');
INSERT INTO subjects (name) VALUES ('Maps');
INSERT INTO subjects (name) VALUES ('Markets');
INSERT INTO subjects (name) VALUES ('Mayor (Name)');
INSERT INTO subjects (name) VALUES ('Memorials');
INSERT INTO subjects (name) VALUES ('Mental Health');
INSERT INTO subjects (name) VALUES ('Monuments');
INSERT INTO subjects (name) VALUES ('Motor Vehicles');
INSERT INTO subjects (name) VALUES ('Museums');
INSERT INTO subjects (name) VALUES ('Neighborhoods');
INSERT INTO subjects (name) VALUES ('Nutrition');
INSERT INTO subjects (name) VALUES ('Officials and Employees');
INSERT INTO subjects (name) VALUES ('Parking');
INSERT INTO subjects (name) VALUES ('Parks and Recreation');
INSERT INTO subjects (name) VALUES ('Pensions');
INSERT INTO subjects (name) VALUES ('Pests');
INSERT INTO subjects (name) VALUES ('Police');
INSERT INTO subjects (name) VALUES ('Police - Community Relations');
INSERT INTO subjects (name) VALUES ('Police - Discipline');
INSERT INTO subjects (name) VALUES ('Politics and Government');
INSERT INTO subjects (name) VALUES ('Pollution');
INSERT INTO subjects (name) VALUES ('Poverty');
INSERT INTO subjects (name) VALUES ('Prices');
INSERT INTO subjects (name) VALUES ('Purchasing Methods');
INSERT INTO subjects (name) VALUES ('Public Authorities');
INSERT INTO subjects (name) VALUES ('Public Welfare');
INSERT INTO subjects (name) VALUES ('Queens');
INSERT INTO subjects (name) VALUES ('Real Property');
INSERT INTO subjects (name) VALUES ('Records');
INSERT INTO subjects (name) VALUES ('Recreation');
INSERT INTO subjects (name) VALUES ('Recycling');
INSERT INTO subjects (name) VALUES ('Refuse and Refuse Disposal');
INSERT INTO subjects (name) VALUES ('Religions');
INSERT INTO subjects (name) VALUES ('Rent Control');
INSERT INTO subjects (name) VALUES ('Rent Stabilization Law');
INSERT INTO subjects (name) VALUES ('Restaurants');
INSERT INTO subjects (name) VALUES ('Retail');
INSERT INTO subjects (name) VALUES ('Rivers');
INSERT INTO subjects (name) VALUES ('Sanitation');
INSERT INTO subjects (name) VALUES ('Schools');
INSERT INTO subjects (name) VALUES ('Schools - Administration');
INSERT INTO subjects (name) VALUES ('Schools - Charter');
INSERT INTO subjects (name) VALUES ('Schools - Parochial');
INSERT INTO subjects (name) VALUES ('Schools - Private');
INSERT INTO subjects (name) VALUES ('Schools - Buildings');
INSERT INTO subjects (name) VALUES ('Sewage');
INSERT INTO subjects (name) VALUES ('Small Business');
INSERT INTO subjects (name) VALUES ('Snow Removal');
INSERT INTO subjects (name) VALUES ('Special Districts');
INSERT INTO subjects (name) VALUES ('State of New York');
INSERT INTO subjects (name) VALUES ('Staten Island');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Street Vendors');
INSERT INTO subjects (name) VALUES ('Streets - Maintenance and Repair');
INSERT INTO subjects (name) VALUES ('Streets and Highways');
INSERT INTO subjects (name) VALUES ('Students');
INSERT INTO subjects (name) VALUES ('Subways');
INSERT INTO subjects (name) VALUES ('Subways - Stations');
INSERT INTO subjects (name) VALUES ('Supplies');
INSERT INTO subjects (name) VALUES ('Surveying');
INSERT INTO subjects (name) VALUES ('Taxation');
INSERT INTO subjects (name) VALUES ('Taxation - Exemption from');
INSERT INTO subjects (name) VALUES ('Taxation - Real Property');
INSERT INTO subjects (name) VALUES ('Taxicabs');
INSERT INTO subjects (name) VALUES ('Teachers');
INSERT INTO subjects (name) VALUES ('Television');
INSERT INTO subjects (name) VALUES ('Terminals');
INSERT INTO subjects (name) VALUES ('Terrorism');
INSERT INTO subjects (name) VALUES ('Toilets');
INSERT INTO subjects (name) VALUES ('Tolls');
INSERT INTO subjects (name) VALUES ('Tourists');
INSERT INTO subjects (name) VALUES ('Traffic and Parking');
INSERT INTO subjects (name) VALUES ('Traffic Safety');
INSERT INTO subjects (name) VALUES ('Transit');
INSERT INTO subjects (name) VALUES ('Transit - Rapid');
INSERT INTO subjects (name) VALUES ('Transportation');
INSERT INTO subjects (name) VALUES ('Transportation - Finance');
INSERT INTO subjects (name) VALUES ('Transportation - School');
INSERT INTO subjects (name) VALUES ('Transportation- Planning');
INSERT INTO subjects (name) VALUES ('Trees');
INSERT INTO subjects (name) VALUES ('Trusts and Estates');
INSERT INTO subjects (name) VALUES ('Universities and Colleges');
INSERT INTO subjects (name) VALUES ('Vendors and Contracts');
INSERT INTO subjects (name) VALUES ('Veterans');
INSERT INTO subjects (name) VALUES ('Volunteers');
INSERT INTO subjects (name) VALUES ('Water');
INSERT INTO subjects (name) VALUES ('Water Supply');
INSERT INTO subjects (name) VALUES ('Weapons');
INSERT INTO subjects (name) VALUES ('Weather');
INSERT INTO subjects (name) VALUES ('Women');
INSERT INTO subjects (name) VALUES ('World Trade Center');
INSERT INTO subjects (name) VALUES ('Youth');


CREATE TABLE report_types (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO report_types (name) VALUES ('Adjudications / Decisions');
INSERT INTO report_types (name) VALUES ('Audit Report');
INSERT INTO report_types (name) VALUES ('Brochures');
INSERT INTO report_types (name) VALUES ('Budget / Finance');
INSERT INTO report_types (name) VALUES ('Bulletins');
INSERT INTO report_types (name) VALUES ('Calendars');
INSERT INTO report_types (name) VALUES ('Data / Statistics');
INSERT INTO report_types (name) VALUES ('Directives');
INSERT INTO report_types (name) VALUES ('Environmental Impact Statements - Draft');
INSERT INTO report_types (name) VALUES ('Environmental Impact Statements - Final');
INSERT INTO report_types (name) VALUES ('Executive Orders');
INSERT INTO report_types (name) VALUES ('Guides');
INSERT INTO report_types (name) VALUES ('Laws / Legislation');
INSERT INTO report_types (name) VALUES ('Manuals / Directories');
INSERT INTO report_types (name) VALUES ('Minutes');
INSERT INTO report_types (name) VALUES ('Newsletters / Other Serial Publications');
INSERT INTO report_types (name) VALUES ('Other');
INSERT INTO report_types (name) VALUES ('Plans');
INSERT INTO report_types (name) VALUES ('Press Releases');
INSERT INTO report_types (name) VALUES ('Proceedings');
INSERT INTO report_types (name) VALUES ('Reports - Annual');
INSERT INTO report_types (name) VALUES ('Reports - Biennial');
INSERT INTO report_types (name) VALUES ('Reports - Monthly');
INSERT INTO report_types (name) VALUES ('Reports - Weekly');
INSERT INTO report_types (name) VALUES ('Reports - Other (Consultant/Staff)');
INSERT INTO report_types (name) VALUES ('Studies');

CREATE TABLE languages (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO languages (name) VALUES ('English');
INSERT INTO languages (name) VALUES ('Spanish');
INSERT INTO languages (name) VALUES ('Chinese');
INSERT INTO languages (name) VALUES ('Russian');
INSERT INTO languages (name) VALUES ('Arabic');
INSERT INTO languages (name) VALUES ('Bengali');
INSERT INTO languages (name) VALUES ('French');
INSERT INTO languages (name) VALUES ('Haitian Creole');
INSERT INTO languages (name) VALUES ('Italian');
INSERT INTO languages (name) VALUES ('Korean');
INSERT INTO languages (name) VALUES ('Polish');
INSERT INTO languages (name) VALUES ('Urdu');
INSERT INTO languages (name) VALUES ('Yiddish');

CREATE TABLE boroughs (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO boroughs (name) VALUES ('Bronx');
INSERT INTO boroughs (name) VALUES ('Brooklyn');
INSERT INTO boroughs (name) VALUES ('Manhattan');
INSERT INTO boroughs (name) VALUES ('Queens');
INSERT INTO boroughs (name) VALUES ('Staten Island');

CREATE TABLE school_districts (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO school_districts (name) VALUES ('District 1');
INSERT INTO school_districts (name) VALUES ('District 2');
INSERT INTO school_districts (name) VALUES ('District 3');
INSERT INTO school_districts (name) VALUES ('District 4');
INSERT INTO school_districts (name) VALUES ('District 5');
INSERT INTO school_districts (name) VALUES ('District 6');
INSERT INTO school_districts (name) VALUES ('District 7');
INSERT INTO school_districts (name) VALUES ('District 8');
INSERT INTO school_districts (name) VALUES ('District 9');
INSERT INTO school_districts (name) VALUES ('District 10');
INSERT INTO school_districts (name) VALUES ('District 11');
INSERT INTO school_districts (name) VALUES ('District 12');
INSERT INTO school_districts (name) VALUES ('District 13');
INSERT INTO school_districts (name) VALUES ('District 14');
INSERT INTO school_districts (name) VALUES ('District 15');
INSERT INTO school_districts (name) VALUES ('District 16');
INSERT INTO school_districts (name) VALUES ('District 17');
INSERT INTO school_districts (name) VALUES ('District 18');
INSERT INTO school_districts (name) VALUES ('District 19');
INSERT INTO school_districts (name) VALUES ('District 20');
INSERT INTO school_districts (name) VALUES ('District 21');
INSERT INTO school_districts (name) VALUES ('District 22');
INSERT INTO school_districts (name) VALUES ('District 23');
INSERT INTO school_districts (name) VALUES ('District 24');
INSERT INTO school_districts (name) VALUES ('District 25');
INSERT INTO school_districts (name) VALUES ('District 26');
INSERT INTO school_districts (name) VALUES ('District 27');
INSERT INTO school_districts (name) VALUES ('District 28');
INSERT INTO school_districts (name) VALUES ('District 29');
INSERT INTO school_districts (name) VALUES ('District 30');
INSERT INTO school_districts (name) VALUES ('District 31');
INSERT INTO school_districts (name) VALUES ('District 32');
INSERT INTO school_districts (name) VALUES ('District 75');
INSERT INTO school_districts (name) VALUES ('District 79');

CREATE TABLE community_board_districts (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO school_districts (name) VALUES ('Bronx 1');
INSERT INTO school_districts (name) VALUES ('Bronx 2');
INSERT INTO school_districts (name) VALUES ('Bronx 3');
INSERT INTO school_districts (name) VALUES ('Bronx 4');
INSERT INTO school_districts (name) VALUES ('Bronx 5');
INSERT INTO school_districts (name) VALUES ('Bronx 6');
INSERT INTO school_districts (name) VALUES ('Bronx 7');
INSERT INTO school_districts (name) VALUES ('Bronx 8');
INSERT INTO school_districts (name) VALUES ('Bronx 9');
INSERT INTO school_districts (name) VALUES ('Bronx 10');
INSERT INTO school_districts (name) VALUES ('Bronx 11');
INSERT INTO school_districts (name) VALUES ('Bronx 12');
INSERT INTO school_districts (name) VALUES ('Brooklyn 1');
INSERT INTO school_districts (name) VALUES ('Brooklyn 2');
INSERT INTO school_districts (name) VALUES ('Brooklyn 3');
INSERT INTO school_districts (name) VALUES ('Brooklyn 4');
INSERT INTO school_districts (name) VALUES ('Brooklyn 5');
INSERT INTO school_districts (name) VALUES ('Brooklyn 6');
INSERT INTO school_districts (name) VALUES ('Brooklyn 7');
INSERT INTO school_districts (name) VALUES ('Brooklyn 8');
INSERT INTO school_districts (name) VALUES ('Brooklyn 9');
INSERT INTO school_districts (name) VALUES ('Brooklyn 10');
INSERT INTO school_districts (name) VALUES ('Brooklyn 11');
INSERT INTO school_districts (name) VALUES ('Brooklyn 12');
INSERT INTO school_districts (name) VALUES ('Brooklyn 13');
INSERT INTO school_districts (name) VALUES ('Brooklyn 14');
INSERT INTO school_districts (name) VALUES ('Brooklyn 15');
INSERT INTO school_districts (name) VALUES ('Brooklyn 16');
INSERT INTO school_districts (name) VALUES ('Brooklyn 17');
INSERT INTO school_districts (name) VALUES ('Brooklyn 18');
INSERT INTO school_districts (name) VALUES ('Manhattan 1');
INSERT INTO school_districts (name) VALUES ('Manhattan 2');
INSERT INTO school_districts (name) VALUES ('Manhattan 3');
INSERT INTO school_districts (name) VALUES ('Manhattan 4');
INSERT INTO school_districts (name) VALUES ('Manhattan 5');
INSERT INTO school_districts (name) VALUES ('Manhattan 6');
INSERT INTO school_districts (name) VALUES ('Manhattan 7');
INSERT INTO school_districts (name) VALUES ('Manhattan 8');
INSERT INTO school_districts (name) VALUES ('Manhattan 9');
INSERT INTO school_districts (name) VALUES ('Manhattan 10');
INSERT INTO school_districts (name) VALUES ('Manhattan 11');
INSERT INTO school_districts (name) VALUES ('Manhattan 12');
INSERT INTO school_districts (name) VALUES ('Queens 1');
INSERT INTO school_districts (name) VALUES ('Queens 2');
INSERT INTO school_districts (name) VALUES ('Queens 3');
INSERT INTO school_districts (name) VALUES ('Queens 4');
INSERT INTO school_districts (name) VALUES ('Queens 5');
INSERT INTO school_districts (name) VALUES ('Queens 6');
INSERT INTO school_districts (name) VALUES ('Queens 7');
INSERT INTO school_districts (name) VALUES ('Queens 8');
INSERT INTO school_districts (name) VALUES ('Queens 9');
INSERT INTO school_districts (name) VALUES ('Queens 10');
INSERT INTO school_districts (name) VALUES ('Queens 11');
INSERT INTO school_districts (name) VALUES ('Queens 12');
INSERT INTO school_districts (name) VALUES ('Queens 13');
INSERT INTO school_districts (name) VALUES ('Queens 14');
INSERT INTO school_districts (name) VALUES ('Staten Island 1');
INSERT INTO school_districts (name) VALUES ('Staten Island 2');
INSERT INTO school_districts (name) VALUES ('Staten Island 3');